"""last seen, unique Recipe.title

Revision ID: 241d40abc6ae
Revises: 629c02225682
Create Date: 2018-10-12 09:52:20.814609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241d40abc6ae'
down_revision = '629c02225682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'recipe', ['title'])
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_constraint(None, 'recipe', type_='unique')
    # ### end Alembic commands ###
