"""empty message

Revision ID: 629c02225682
Revises: 5c469ff14715
Create Date: 2018-10-09 22:32:57.546474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629c02225682'
down_revision = '5c469ff14715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image_url', sa.String(length=200), nullable=True))
    op.add_column('recipe', sa.Column('ingredients', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('recipe', sa.Column('rdy_in_minutes', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('servings', sa.Integer(), nullable=True))
    op.add_column('recipe', sa.Column('steps', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('recipe', sa.Column('title', sa.String(length=60), nullable=True))
    op.add_column('recipe', sa.Column('url', sa.String(length=200), nullable=True))
    op.add_column('recipe', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'recipe', ['url'])
    op.drop_constraint('recipe_added_by_fkey', 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'user', ['user_id'], ['id'])
    op.drop_column('recipe', 'added_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key('recipe_added_by_fkey', 'recipe', 'user', ['added_by'], ['id'])
    op.drop_constraint(None, 'recipe', type_='unique')
    op.drop_column('recipe', 'user_id')
    op.drop_column('recipe', 'url')
    op.drop_column('recipe', 'title')
    op.drop_column('recipe', 'steps')
    op.drop_column('recipe', 'servings')
    op.drop_column('recipe', 'rdy_in_minutes')
    op.drop_column('recipe', 'ingredients')
    op.drop_column('recipe', 'image_url')
    # ### end Alembic commands ###
