"""empty message

Revision ID: b1019340f43c
Revises: 629c02225682
Create Date: 2018-10-11 14:59:24.949619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1019340f43c'
down_revision = '629c02225682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'recipe', ['title'])
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_constraint(None, 'recipe', type_='unique')
    # ### end Alembic commands ###
